DROP TABLE IF EXISTS items
CASCADE;

CREATE TABLE items
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  is_sold BOOLEAN DEFAULT FALSE,
  is_featured BOOLEAN DEFAULT FALSE,
  price INTEGER NOT NULL,
  image_url VARCHAR(255) DEFAULT 'https://i.imgur.com/gZ5yBwv.jpg',
  description TEXT DEFAULT '',
  title VARCHAR(255) NOT NULL,
  posting_date TIMESTAMP DEFAULT NOW() ,
  stock INTEGER DEFAULT 1,
  is_viewable BOOLEAN DEFAULT TRUE,
  city VARCHAR(255)
);


GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to labber;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public to labber;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public to labber;
