DROP TABLE IF EXISTS favorites CASCADE;

CREATE TABLE favorites(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users( id ) ON DELETE CASCADE,
  item_id INTEGER REFERENCES items( id ) ON DELETE CASCADE,
  date TIMESTAMP DEFAULT NOW()
);
