DROP TABLE IF EXISTS favorites CASCADE;

CREATE TABLE favorites(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users( id ) ON DELETE CASCADE,
  item_id INTEGER REFERENCES items( id ) ON DELETE CASCADE,
  date TIMESTAMP DEFAULT NOW()
);


GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to labber;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public to labber;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public to labber;
